# Generated by Django 3.2.5 on 2021-07-14 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_text', models.CharField(max_length=20)),
                ('major_text', models.CharField(max_length=20)),
                ('score_int', models.IntegerField(max_length=3)),
                ('range_int', models.IntegerField(max_length=10)),
                ('sci_or_lib', models.BooleanField()),
                ('adv_or_com', models.BooleanField()),
            ],
        ),
    ]
