# Generated by Django 3.2.5 on 2021-07-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeapplication',
            name='year_int',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='range_int',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='score_int',
            field=models.IntegerField(),
        ),
    ]
