# Generated by Django 3.2.5 on 2021-07-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_alter_collegeapplication_year_int'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeapplication',
            name='major_situation_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='collegeapplication',
            name='year_int',
            field=models.IntegerField(),
        ),
    ]
