# Generated by Django 3.2.5 on 2021-07-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_auto_20210714_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeapplication',
            name='is_211',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='collegeapplication',
            name='is_985',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterModelTable(
            name='collegeapplication',
            table='recommend_application',
        ),
    ]
